sudo: false
language: node_js
env:
  - PKG_CONFIG_PATH=$HOME/libck/lib/pkgconfig CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - libfuse-dev
    - fuse
    - build-essential
    - pkg-config
    - gcc-4.8
    - g++-4.8

node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58c9d92f0d5882f60391
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - $CXX --version
  - npm install npm
  - mv node_modules npm
  - LOCALNPM=`pwd`/npm/.bin/npm
  - LOCALBUILD=`pwd`
  - PARENTNODE=$(dirname `which node`)
  - PARENTNODE=$(dirname "$PARENTNODE")
  - npm/.bin/npm --version  
  - npm/.bin/npm install -g node-gyp-install
  - node-gyp-install
  - wget http://concurrencykit.org/releases/ck-0.4.5.tar.gz
  - echo $PKG_CONFIG_PATH
  - tar -zxvf ck-0.4.5.tar.gz
  - cd ck-0.4.5 && ./configure --prefix=$HOME/libck && make && make install
  - cd ..
  - BUILD_DIR=`pwd`
  - echo $PARENTNODE
  - echo $LOCALBUILD
  - ls `which node`
  - npm/.bin/npm install

install:
